name: "Build and Copy"
on:
  push:
    branches: [ dev ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle

      - name: Build with gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Archive the jar
        run: |
          mkdir -p target/deploy
          cp build/libs/demo-0.0.1-SNAPSHOT.jar target/deploy/demo.jar

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy
        run: |
          echo "🚀 Deployment started"
          scp -P ${{ secrets.SSH_PORT }} target/deploy/demo.jar \
              shubham@192.168.130.3:/home/shubham/DEMODIR/demo.jar
          
          ssh -p ${{ secrets.SSH_PORT }} shubham@192.168.130.3 "
          sudo mv /home/shubham/DEMODIR/demo.jar /root/modem/ && sudo chown root:root /root/modem/demo.jar
          "
          echo '✅ Deployment completed'
          
