name: Multitest CICD Pipeline

on:
  push:
    branches:
      - prod1
      - dev1
      - uat1

jobs:

  deploy-dev:
    name: Deploy to Dev1
    runs-on: self-hosted
    if: github.ref == 'refs/heads/dev1'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Dev1
        run: |
          echo "Deploying to Dev1"

  deploy-uat:
    name: Deploy to UAT1
    runs-on: self-hosted
    if: github.ref == 'refs/heads/uat1'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to UAT1
        run: |
          echo "Deploying to UAT1"

  deploy-prod:
    name: Deploy to Prod1
    runs-on: self-hosted
    if: github.ref == 'refs/heads/prod1'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Prod1
        run: |
          echo "Deploying to Prod1"
