name: "Build and Copy"
on:
  push:
    branches: [ prodaws_selhostedrunner_ansible ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle

      - name: Build with gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Archive the jar
        run: |
          mkdir -p /home/shubham/target/deploy
          cp build/libs/demo-0.0.1-SNAPSHOT.jar /home/shubham/target/deploy/demo.jar

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: running a ansible playbook
        run: |
          ansible-playbook -i /ANSIBLE/INVENTORY/hosts /ANSIBLE/PLAYBOOK/remote.yml
          echo "Playbook run completed..." 
