name: "Build and Copy"
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle

      - name: check java version
        run: java --version


      - name: Build with gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Archive the jar
        run: |
          mkdir -p target/deploy
          cp build/libs/demo-0.0.1-SNAPSHOT.jar target/deploy/demo.jar

      - uses: actions/upload-artifact@v4
        with:
          name: jar
          path: target/deploy/demo.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - uses: actions/download-artifact@v4
        with:
          name: jar
          path: .

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          echo "🚀 Deployment started"
          scp -P -o StrictHostKeyChecking=no ${{ secrets.SSH_PORT }} demo.jar ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEST_DIR }}/demo.jar


## move into place on remote with sudo
#            ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
#            "sudo mv /tmp/demo.jar ${{ secrets.DEST_DIR }}/demo.jar && sudo chown root:root ${{ secrets.DEST_DIR }}/demo.jar"
#            echo "✅ Deployment completed"
